required = [
    "github.com/docker/libkv",
    "github.com/hashicorp/consul",
#    "github.com/coreos/etcd",
    "github.com/kr/pretty",
]

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/cut"

[[constraint]]
  name = "github.com/akaspin/logx"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/supervisor"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v14"

#[[constraint]]
#  name = "github.com/docker/libkv"
#  version = "v0.2.1"
#
#[[constraint]]
#  name = "github.com/coreos/etcd"
#  revision = "785a5a11edf826f8d3e3396c33bf38c717b6225e"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/RoaringBitmap/roaring"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/ryanuber/columnize"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"
