required = [
    "github.com/kr/pretty",
]

[[constraint]]
  name = "github.com/akaspin/cut"
  branch = "master"

[[constraint]]
  name = "github.com/akaspin/logx"
  version = "2.1.1"

[[constraint]]
  name = "github.com/akaspin/supervisor"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v14"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  branch = "master"

[[constraint]]
  name = "github.com/RoaringBitmap/roaring"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  branch = "master"
#  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"
#  version = "v1.2.0"

[[constraint]]
  name = "github.com/ryanuber/columnize"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  branch = "master"

[[constraint]]
  name = "github.com/kr/pretty"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v1.13.1"
