
[[constraint]]
  version = "2.2.0"
  name = "github.com/akaspin/concurrency"

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/cut"

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/logx"

[[constraint]]
  branch = "master"
  name = "github.com/akaspin/supervisor"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-systemd"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-memdb"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/memberlist"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"
