name: Soil
description: Soil


URL: https://akaspin.github.com
baseurl: "/soil"

exclude: []

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

permalink: pretty

#gems:
#- jekyll-redirect-from
#- rouge
